<?php
/**
 * @file
 * Code for the ELMCIP search feature.
 */

include_once 'elmcip_search.features.inc';

/**
 * Processes variables for search-api-page-full-page.tpl.php
 */
function elmcip_search_preprocess_search_api_page_full_page(&$variables) {
  $variables['form']['#attributes'] = ['class' => 'container-inline search-api-page-form'];
  $variables['form']['text']['#weight'] = 1;
  unset($variables['form']['form']['keys_1']['#title']);
}
