<?php declare(strict_types=1);

/**
 * Implements hook_node_presave().
 */
function elmcip_person_node_presave($node) {
  if ($node->type === 'person') {
    $entity_updated = entity_metadata_wrapper('node', $node);
    $person = new elmcip_person($entity_updated->field_first_name->value(),
      $entity_updated->field_middle_name->value(),
      $entity_updated->field_last_name->value());
    $entity_updated->title->set($person->person_title());
  }
}

/**
 * Implements hook_form_alter().
 */
function elmcip_person_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'person_node_form':
      $form['title']['#type'] = 'hidden';
      $form['title']['#default_value'] = 'ELMCIP auto generated - dummy';
      break;
  }
}
